package com.cyberbullies.iceshu4.enums;

public enum Departments {
    COMPUTER_ENGINEERING,
    ARTIFICIAL_INTELLIGENCE_ENGINEERING,
    ELECTRICAL_AND_ELECTRONICS_ENGINEERING,
    MECHANICAL_ENGINEERING,
    INDUSTRIAL_ENGINEERING,
    CIVIL_ENGINEERING,
}
