INSERT INTO STUDENT (ID, NAME, SURNAME, ROLE, PASSWORD, EMAIL, BIRTH_DATE, ABOUT, ADDRESS, SCHOOL_ID) VALUES (1, 'Yunus', 'Terzi', NULL, '123', 'yunus@gmail.com', '31.10.2001', '', '', '');
INSERT INTO STUDENT (ID, NAME, SURNAME, ROLE, PASSWORD, EMAIL, BIRTH_DATE, ABOUT, ADDRESS, SCHOOL_ID) VALUES (2, 'Numan', 'Kafadar', NULL, '123', 'numan@gmail.com', '31.10.2001', '', '', '');
INSERT INTO STUDENT (ID, NAME, SURNAME, ROLE, PASSWORD, EMAIL, BIRTH_DATE, ABOUT, ADDRESS, SCHOOL_ID) VALUES (3, 'Umut', 'Gungor', NULL, '123', 'umut@gmail.com', '31.10.2001', '', '', '');

INSERT INTO DEPARTMENT (ID, NAME) VALUES (1, 'COMPUTER ENGINEERING');
INSERT INTO DEPARTMENT (ID, NAME) VALUES (2, 'ARTIFICIAL INTELLIGENCE ENGINEERING');
INSERT INTO DEPARTMENT (ID, NAME) VALUES (3, 'ELECTRONICAL AND ELECTRONICS ENGINEERING');
INSERT INTO DEPARTMENT (ID, NAME) VALUES (4, 'MECHANICAL ENGINEERING');
INSERT INTO DEPARTMENT (ID, NAME) VALUES (5, 'INDUSTRY ENGINEERING');
INSERT INTO DEPARTMENT (ID, NAME) VALUES (6, 'CIVIL ENGINEERING');