INSERT INTO DEPARTMENT (ID, NAME) VALUES (1, 'COMPUTER ENGINEERING');
INSERT INTO DEPARTMENT (ID, NAME) VALUES (2, 'ARTIFICIAL INTELLIGENCE ENGINEERING');
INSERT INTO DEPARTMENT (ID, NAME) VALUES (3, 'ELECTRONICAL AND ELECTRONICS ENGINEERING');
INSERT INTO DEPARTMENT (ID, NAME) VALUES (4, 'MECHANICAL ENGINEERING');
INSERT INTO DEPARTMENT (ID, NAME) VALUES (5, 'INDUSTRY ENGINEERING');
INSERT INTO DEPARTMENT (ID, NAME) VALUES (6, 'CIVIL ENGINEERING');

INSERT INTO STUDENT (NAME, SURNAME, ROLE, PASSWORD, EMAIL, BIRTH_DATE, ABOUT, ADDRESS, SCHOOL_ID, DEPARTMENT_ID) VALUES ('Yunus', 'Terzi', 0, '$2a$10$eNPZWR/LvI/8OvDJzlUzrO4hg7ZOJ/Yvuhg/RUqbv5zf6/dONXb6.', 'yunus@gmail.com', '31.10.2001', '', '', '2200356021', 1);
INSERT INTO STUDENT (NAME, SURNAME, ROLE, PASSWORD, EMAIL, BIRTH_DATE, ABOUT, ADDRESS, SCHOOL_ID, DEPARTMENT_ID) VALUES ('Numan', 'Kafadar', 0, '$2a$10$eNPZWR/LvI/8OvDJzlUzrO4hg7ZOJ/Yvuhg/RUqbv5zf6/dONXb6.', 'numan@gmail.com', '31.10.2001', '', '', '21946242', 4);
INSERT INTO STUDENT (NAME, SURNAME, ROLE, PASSWORD, EMAIL, BIRTH_DATE, ABOUT, ADDRESS, SCHOOL_ID, DEPARTMENT_ID) VALUES ('Umut', 'Gungor', 0, '$2a$10$eNPZWR/LvI/8OvDJzlUzrO4hg7ZOJ/Yvuhg/RUqbv5zf6/dONXb6.', 'umut@gmail.com', '31.10.2001', '', '', '21946198', 3);